-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 13:33:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBEventList
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBEventList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBEventList` DEFAULT CHARACTER SET utf8 ;
USE `DBEventList` ;

-- -----------------------------------------------------
-- Table `DBEventList`.`MeetingSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBEventList`.`MeetingSchedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(500) NOT NULL DEFAULT 'reserve',
  `start` DATETIME NOT NULL,
  `ending` DATETIME NOT NULL,
  `notice` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
